### ISSUE TITLE
Bug with .neon configuration

### ISSUE THREAD

**Issue by BigOHenry** [Carrooi/Nette-ImagesManager#10]
Hello, i think there is a bug with `.neon` configuration:

```
extensions:
    images: Carrooi\ImagesManager\DI\ImagesManagerExtension

images:
    source:
        basePath: %wwwDir%/gallery
        baseUrl: http://www.domain.cz/gallery
```

So i think this is right, but still getting this error:

```
Nette\InvalidStateException

Unknown configuration option images.source.
```
